### ISSUE TITLE
SSL problem on Yapbam.net 

### ISSUE THREAD

**Issue by marcoM32** [yapbam/yapbam#6]
On the Yapbam.net website the https certificate has expired this is causing some errors in the software start-up and also users who try to access the site receive an error message: 

![Cattura](https://user-images.githubusercontent.com/16719549/140787204-ad48e7a7-5780-459e-8793-7d60924374e9.PNG)

`
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1622)
	... 24 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:238)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:146)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:85)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
	... 30 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Sun Oct 24 08:42:10 CEST 2021
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
	at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at sun.securi
`

you can control?

**Comment by fathzer** [comment]
Hi Marco,
Yes, I saw it yesterday :-(
The bad news is, it is a recurrent problem with the solution I use: the wonderful (when it works https://hub.docker.com/r/steveltn/https-portal/).
Solving it is on my list ;-)
Thanks for the alert.
Best resgards,
Jean-Marc

**Comment by fathzer** [comment]
Fixed by updating https-portal :-)

**Comment by marcoM32** [comment]
Thanks so much for the work
